spring:
  application:
    name: shop
  datasource:
    password: LKCzka2233
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://rm-uf6w4ps6s94g83g7eao.mysql.rds.aliyuncs.com:3306/mall?useUnicode=true&characterEncoding=utf8&useSSL=false
      #最小空闲链接
      min-idle: 5
      default-auto-commit: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  address: localhost
  port: 8088