server:
  port: 8080
  address: localhost
  servlet:
    context-path: /oauth2

spring:
  application:
    name: oauth2

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456

mybatis-plus:
  global-config:
    db-config:
      table-prefix: sys_
  mapper-locations: /mapper/*.xml

swagger:
  title: SpringBoot-ACGN
  description: none
  name: lkc39miku_cn
  url: none
  email: lkc39miku_cn@outlook.com
  version: 1.0
  enable: true
  path-mapping: /
  address-enabled: false